# This is the configuration file for https://marcopisco.com/blog

remote_theme: mmistakes/minimal-mistakes
plugins:
- jekyll-remote-theme
title: marcopisco.com/blog
description: marco pisco's personal blog
