# This is the configuration file for https://marcopisco.com/blog

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: marcopisco.com/blog
description: marco pisco''s personal blog
