# This is the configuration file for https://marcopisco.com/blog

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marco Pisco
email: marco@marcopisco.com
description: >- # this means to ignore newlines until "baseurl:"
  Marco Pisco's personal website
twitter_username: marco_pisco
github_username: marpisco
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /posts/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Marco Pisco"
  avatar : "/assets/images/biophoto.jpg"
  bio    : "Student and Developer. Technology enthusiast"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/marco_pisco"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marpisco"
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:marco@marcopisco.com"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://ciberlandia.pt/@marcopisco"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/marco_pisco"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marpisco"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://ciberlandia.pt/@marcopisco"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
